require 'rubygems'
require 'spork'
#uncomment the following line to use spork with the debugger
#require 'spork/ext/ruby-debug'

Spork.prefork do

  # This file is copied to spec/ when you run 'rails generate rspec:install'
  ENV["RAILS_ENV"] ||= 'test'
  if ENV['COVERAGE']
    require 'simplecov'
    SimpleCov.start 'rails'
    SimpleCov.command_name "spec"
  end
  require File.expand_path("../../config/environment", __FILE__)
  require 'rspec/rails'
  require 'rspec/autorun'
  require 'database_cleaner'
  #require 'capybara/rspec'
  #require 'webmock/rspec'


  # Requires supporting ruby files with custom matchers and macros, etc,
  # in spec/support/ and its subdirectories.
  Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}

  require 'factory_girl'

  require 'database_cleaner'

  # This file was generated by the `rspec --init` command. Conventionally, all
  # specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
  # Require this file using `require "spec_helper"` to ensure that it is only
  # loaded once.
  #
  # See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
  RSpec.configure do |config|
    config.treat_symbols_as_metadata_keys_with_true_values = true
    config.run_all_when_everything_filtered = true

    # Run specs in random order to surface order dependencies. If you find an
    # order dependency and want to debug it, you can fix the order by providing
    # the seed, which is printed after each run.
    #     --seed 1234
    config.order = 'random'

    config.use_transactional_fixtures = false

    config.include Devise::TestHelpers, type: :controller
    config.include Warden::Test::Helpers, type: :feature
    config.include FeatureSupport, type: :feature

    config.before(:suite) do
      DatabaseCleaner.strategy = :truncation
      DatabaseCleaner.clean_with(:truncation)
    end

    config.before(:all) do
      WebMock.allow_net_connect!
    end

    config.before(:each) do
      DatabaseCleaner.start
    end

    config.after(:each) do
      DatabaseCleaner.clean
    end
  end

end

Spork.each_run do
  require 'factory_girl_rails'
   load "#{Rails.root}/config/routes.rb"
    # Hack to ensure models get reloaded by Spork - remove as soon as this is fixed in Spork.
   # Silence warnings to avoid all the 'warning: already initialized constant' messages that
   # appear for constants defined in the models.
     Dir["#{Rails.root}/app/models/**/*.rb"].each {|model| load  model}
     Dir["#{Rails.root}/app/repository_models/**/*.rb"].each {|model| load  model}
end
